# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usb_storage" "sd_mod" "sdhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-8f249fa6-01b3-4835-b8d6-160c9b20de05";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-8f249fa6-01b3-4835-b8d6-160c9b20de05".device = "/dev/disk/by-uuid/8f249fa6-01b3-4835-b8d6-160c9b20de05";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/75B6-11B3";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-3011b93d-b77f-4bfd-9bce-e017cd20ee87"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
