
# Commands that should be applied only for interactive shells.
[[ $- == *i* ]] || return
shopt -s histappend
shopt -s expand_aliases
shopt -s cdspell
shopt -s dirspell
shopt -s direxpand
# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize
#jump to direcory without typing cd
shopt -s autocd
# If set, the pattern "**" used in a pathname expansion context will
# match all files and zero or more directories and subdirectories.
shopt -s globstar
export PATH=$HOME/dotfiles/scripts:$PATH
alias e=nvim
HISTCONTROL=ignoreboth

#filter history
export HISTIGNORE="pwd:ls:cd:clear:vim:mv:cp:touch"

alias mpv="flatpak run io.mpv.Mpv"
# enable control-s and control-q
stty -ixon
# Up Arrow
bind '"\e[A": history-search-backward'
# Down Arrow
bind '"\e[B": history-search-forward'
# Space, but magical
bind Space:magic-space



#export FZF_DEFAULT_COMMAND='ag -l --path-to-ignore ~/.ignore --nocolor --hidden -g ""'
export FZF_DEFAULT_COMMAND='rg -l --path-to-ignore ~/.ignore --nocolor --hidden'

export PROMPT_COMMAND='if [ "$(id -u)" -ne 0 ]; then echo "$(date "+%Y-%m-%d.%H:%M:%S") $(pwd) $(history 1)" >> ~/.logs/bash-history-$(date "+%Y-%m-%d").log; fi'
eval "$(zoxide init bash)"


