
# Commands that should be applied only for interactive shells.
[[ $- == *i* ]] || return
shopt -s histappend
shopt -s expand_aliases
shopt -s cdspell
shopt -s dirspell
shopt -s direxpand
# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize
#jump to direcory without typing cd
shopt -s autocd
# If set, the pattern "**" used in a pathname expansion context will
# match all files and zero or more directories and subdirectories.
shopt -s globstar


HISTCONTROL=ignoreboth
HISTSIZE=10000
HISTFILESIZE=2000
#filter history
export HISTIGNORE="pwd:ls:cd:clear:vim:mv:cp:touch"


# enable control-s and control-q
stty -ixon


# Up Arrow
bind '"\e[A": history-search-backward'

# Down Arrow
bind '"\e[B": history-search-forward'
# Space, but magical
bind Space:magic-space
#correct misspeled cd command


export FZF_DEFAULT_COMMAND='ag -l --path-to-ignore ~/.ignore --nocolor --hidden -g ""'
#colorscript exec alpha


eval "$(zoxide init bash)"


if [[ ! -v BASH_COMPLETION_VERSINFO ]]; then
  . "/nix/store/xv3g2xwwndv14wmfnprfi2m5lyk3mca8-bash-completion-2.11/etc/profile.d/bash_completion.sh"
fi

if [[ :$SHELLOPTS: =~ :(vi|emacs): ]]; then
  . /nix/store/dlwmj243w818zfcb5m14rm1nrxq7s3w1-fzf-0.42.0/share/fzf/completion.bash
  . /nix/store/dlwmj243w818zfcb5m14rm1nrxq7s3w1-fzf-0.42.0/share/fzf/key-bindings.bash
fi

eval "$(/nix/store/y6pvmh002crjvajikqpkyqwjczakd7aa-zoxide-0.9.1/bin/zoxide init bash )"

if [[ $TERM != "dumb" ]]; then
  eval "$(/etc/profiles/per-user/kgosi/bin/starship init bash --print-full-init)"
fi

if test -n "$KITTY_INSTALLATION_DIR"; then
  source "$KITTY_INSTALLATION_DIR/shell-integration/bash/kitty.bash"
fi

eval "$(/nix/store/ahynakk2xcjqvc55n1d96i6gm6ssz0gl-direnv-2.32.3/bin/direnv hook bash)"

