name: "NixOS Test"
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v2
      - name: Build System Configuration
        run: |
          nix build .#nixosConfigurations.dell5510.config.system.build.toplevel
